char *s = N_("Ruin Details");
char *s = N_("Name");
char *s = N_("Randomize");
char *s = N_("Description");
char *s = N_("Type");
char *s = N_("0");
char *s = N_("Random Keeper");
char *s = N_("Only Seen By");
char *s = N_("Random Reward");
